### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by smortex**

### CODE REVIEW

**Review by neomilium — DISMISSED** [review]
Puppet version 4.8 (used in Debian stable) is missing

**Comment by smortex** [comment]
The test suite does not run with Puppet 4.8.

**Comment by neomilium** [comment]
But it should be tested against this version as 4.8.2 is one of our targeted OSes, don't you think so ?

**Comment by smortex** [comment]
I added puppet 4.8.2 (version shipped with Debian) to the build matrix.

Since Debian integrates patches for fixing vulnerabilities and backporting features, this is barely a silly test to me (since it's not a test against Debian's Puppet), but if you are confident with this, let's go for it.

**Review by neomilium — APPROVED** [review]

**Pull request merged**
